Repository codepointtku/codepoint-front, pull requests merged in 2021-08, with the labels that each got.

#4 Added Language Support
  components/about/About.tsx
  components/footer/Footer.tsx
  components/header/Header.tsx
  components/profiles/Profiles.tsx
  components/repos/Repos.tsx
  components/set-language/SetLanguage.tsx
  next-i18next.config.js
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/locales/en/common.js
  pages/api/locales/en/footer.js
  pages/api/locales/fi/common.js
  pages/api/locales/fi/footer.js
  pages/index.tsx
Labels: Feature

#6 Add github actions and initial tests
  .eslintrc.js
  .github/workflows/build.yml
  .github/workflows/release.yml
  README.md
  __mocks__/fileMock.js
  __mocks__/styleMock.js
  __mocks__/translateMock.js
  babel.config.js
  components/footer/Footer.test.js
  jest.config.js
  package.json
Labels: Feature

#10 Bringing changes
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/build.yml
  .github/workflows/release.yml
  .gitignore
  README.md
  __mocks__/fileMock.js
  __mocks__/styleMock.js
  __mocks__/translateMock.js
  babel.config.js
  components/about/About.test.js
  components/about/About.tsx
  components/footer/Footer.test.js
  components/footer/Footer.tsx
  components/header/Header.test.js
  components/header/Header.tsx
  components/profiles/Profiles.test.js
  components/profiles/Profiles.tsx
  components/repos/Repos.test.js
  components/repos/Repos.tsx
  components/set-language/SetLanguage.test.js
  components/set-language/SetLanguage.tsx
  jest.config.js
  next-i18next.config.js
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/locales/en/common.js
  pages/api/locales/en/footer.js
  pages/api/locales/fi/common.js
  pages/api/locales/fi/footer.js
  pages/index.tsx
Labels: Revision Required

#8 CSS to SCSS conversion
  components/about/About.tsx
  components/footer/Footer.tsx
  components/header/Header.tsx
  components/profiles/Profiles.tsx
  components/repos/Repos.tsx
  package.json
  pages/_app.tsx
  pages/index.tsx
  styles/Home.module.scss
  styles/globals.scss
Labels: Feature

#14 Initial Dockerization
  Dockerfile
  README.md
Labels: Documentation, Feature

#12 Header, Footer, About us and Navigation styles
  components/about/About.test.js
  components/about/About.tsx
  components/header/Header.test.js
  components/header/Header.tsx
  components/nav/Nav.tsx
  components/repos/Repos.tsx
  next-env.d.ts
  package.json
  pages/index.tsx
  public/about_us.svg
  public/codepoint_logo_lapinakyva2.svg
  public/earth-glyph.svg
  public/icons8-github.svg
  public/icons8-language-60-white.png
  public/icons8-project-orange.svg
  public/icons8-project.svg
  public/info-solid-orange.svg
  public/info-solid.svg
  public/linkedin-blue.svg
  public/team.svg
  public/users-solid-orange.svg
  public/users-solid.svg
  styles/Home.module.scss
  styles/globals.scss
Labels: Feature

#13 Projects and members pages design implementation.
  components/profiles/Profiles.test.js
  components/profiles/Profiles.tsx
  components/repos/Repos.test.js
  components/repos/Repos.tsx
  package.json
  public/earth.svg
  public/github.svg
  public/linkedin.svg
  public/members.webp
  styles/Profiles.module.scss
  styles/Repos.module.scss
Labels: Feature

#15 Feature/docsify
  docs/.nojekyll
  docs/README.md
  docs/index.html
Labels: Documentation

#20 Design implementation for members and projects page
  components/profiles/Profiles.test.js
  components/profiles/Profiles.tsx
  components/repos/Repos.test.js
  components/repos/Repos.tsx
  public/earth.svg
  public/github.svg
  public/linkedin.svg
  public/members.webp
  styles/Profiles.module.scss
  styles/Repos.module.scss
Labels: Feature

#21 About, Header, Nav, Profiles, Repos updated
  components/about/About.test.js
  components/about/About.tsx
  components/header/Header.test.js
  components/header/Header.tsx
  components/nav/Nav.tsx
  components/profiles/Profiles.tsx
  components/repos/Repos.tsx
  package.json
  pages/index.tsx
  public/about_us.svg
  public/codepoint_logo_lapinakyva2.svg
  public/codepoint_logo_transparent.webp
  public/earth.svg
  public/github.svg
  public/github.webp
  public/icons8-language-60-white.webp
  public/info-orange.webp
  public/info-solid-orange.svg
  public/info-solid.svg
  public/info-solid.webp
  public/linkedin.svg
  public/project-orange.svg
  public/project-orange.webp
  public/project.svg
  public/project.webp
  public/team.webp
  public/users-solid-orange.svg
  public/users-solid.svg
  styles/Home.module.scss
  styles/globals.scss
Labels: Feature

#24 Feature/tests graphql
  .eslintrc.js
  apollo-client.ts
  components/profiles/Profiles.test.js
  components/profiles/Profiles.tsx
  components/repos/Repos.test.js
  components/repos/Repos.tsx
  graphql/graphql.ts
  graphql/types/ProfileData.ts
  graphql/types/ProjectData.ts
  jest.config.js
  pages/_app.tsx
  pages/index.tsx
  styles/Home.module.scss
Labels: Feature

#25 add PWA
  next.config.js
  package.json
  pages/_document.js
  public/icons/pwa-192x192.png
  public/icons/pwa-512x512.png
  public/manifest.json
Labels: Feature

#26 update Documentation
  README.md
  docs/README.md
Labels: Feature

#29 Feature/optimize
  .github/workflows/build.yml
  .github/workflows/release.yml
  apollo-client.ts
  components/layouts/layout.tsx
  components/set-language/SetLanguage.tsx
  graphql/graphql.ts
  lib/apolloClient.js
  pages/_app.tsx
  pages/index.tsx
  pages/members.tsx
  pages/projects.tsx
Labels: Feature
